# fly.toml app configuration file generated for beth-todo-app on 2023-10-08T01:12:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beth-todo-app"
primary_region = "bog"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
